theme: jekyll-theme-merlot
title: [Steps]
description: ["All knowledge is, in final analysis, history. 
All sciences are, in the abstact, mathematics. 
All judgements are, in their rationale, statistics.”
--C.R.Rao]
